### PR TITLE
PHP 7 support

### PR DESCRIPTION
**Pull request by GawainLynch**
Parser changes based on [Nikita's documentation](https://github.com/nikic/PHP-Parser/blob/master/UPGRADE-2.0.md)

### CODE REVIEW

**Comment by clemens-tolboom** [comment]
I added `fetch = +refs/pull/*/head:refs/remotes/origin/pr/*` to `.git/config` to test this PR for BC on my old PHP 5.6.18

Running tests `vendor/phpunit/phpunit/phpunit.php` gives

> Undefined index: base
/private/tmp/uml-generator-php/src/OopFilter.php:307

I need to dive into this again and try to fix travis too. Sorry for the delay.

**Comment by GawainLynch** [comment]
Zero stress mate. Travis fixes have been my afternoon today too :smile:

**Comment by clemens-tolboom** [comment]
Running tests on the 'old' version gives same error so this PR is good to go :-)

@GawainLynch thanks!

**Comment by clemens-tolboom** [comment]
https://travis-ci.org/clemens-tolboom/uml-generator-php/builds/164987980

**Pull request merged**
